name: CI - Phase3 Enhanced

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests (Phase 3)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm list --depth=0

      - name: Check Node.js version
        run: node --version

      - name: Run type checking
        run: npm run typecheck

      - name: Run tests with detailed output
        continue-on-error: false
        timeout-minutes: 10
        run: |
          echo "Running tests with increased memory..."
          NODE_OPTIONS='--max-old-space-size=2048' npm test -- --verbose
        env:
          NODE_ENV: test
          CI: true
          VITE_ADMIN_PASSWORD: test_password_for_ci
          VITE_API_URL: https://api.hummbl.io
          VITE_ENVIRONMENT: ci

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-phase3
          path: |
            coverage/
            test-results/
          retention-days: 7
      - name: Upload test summary
        if: always()
        run: |
          mkdir -p .github/actions
          echo "tests: $(date)" > .github/actions/summary.md
          echo "test-status: $?" >> .github/actions/summary.md
      - name: Run build
        run: npm run build
      - name: Start preview server
        run: |
          nohup npx vite preview --host --port 4173 > /dev/null 2>&1 &
          for i in {1..30}; do
            if curl -sSf http://localhost:4173 > /dev/null; then echo "preview up"; break; fi;
            sleep 1;
          done
      - name: Setup Chrome for Lighthouse
        uses: browser-actions/setup-chrome@v1
      - name: Validate models schema
        run: node scripts/validate-models.mjs
      - name: Audit (Lighthouse + Axe)
        continue-on-error: true
        run: node scripts/audit.mjs
        env:
          TARGET_URL: http://localhost:4173
          LH_MIN: 0.9
          AXE_MAX: 0
      - name: Telemetry
        continue-on-error: true
        run: |
          # pass observed timings into telemetry
          export METRIC_TESTS=5.58
          export METRIC_BUILD=1.31
          node scripts/telemetry.mjs
      - name: Upload summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: phase3-summary
          path: .github/actions/summary.md
      - name: Upload audit reports
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: audit-reports
          path: reports
          if-no-files-found: ignore
