name: Integrity Check

on:
  workflow_call:
    inputs:
      reason:
        required: false
        type: string
        default: 'Scheduled check'
      production_url:
        required: false
        type: string
        default: 'https://www.hummbl.io'
    secrets:
      ALERT_WEBHOOK_URL:
        required: false

jobs:
  verify:
    name: Verify Production Integrity
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run integrity check
        id: integrity
        run: |
          echo "Running integrity check against: ${{ inputs.production_url }}"
          node scripts/verify_production_integrity.mjs --url "${{ inputs.production_url }}" || echo "Integrity check failed"
        env:
          NODE_OPTIONS: --max-old-space-size=2048

      - name: Send alert on failure
        if: failure() && github.event_name != 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const webhookUrl = process.env.ALERT_WEBHOOK_URL;
            if (!webhookUrl) {
              console.log('No ALERT_WEBHOOK_URL provided, skipping alert');
              return;
            }
            
            const { data } = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });
            
            await fetch(webhookUrl, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                text: `❌ Integrity check failed for ${context.repo.repo}`,
                run_url: data.html_url,
                run_number: data.run_number,
                reason: '${{ inputs.reason }}'
              })
            });
        env:
          ALERT_WEBHOOK_URL: ${{ secrets.ALERT_WEBHOOK_URL }}
