name: Pre-Deploy Verification

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'public/data/**'
      - 'scripts/**'
      - '.github/workflows/*.yml'

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run build verification
      run: |
        # Run the build process
        npm run build
        
        # Run the verification script
        node scripts/verify_production_integrity.mjs
    
    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          public/data/**
          dist/**
    
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const verificationOutput = fs.readFileSync('verification.log', 'utf8');
          
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `### 🔍 Pre-Deploy Verification Results\n\n\`\`\`\n${verificationOutput}\n\`\`\`\n
✅ Build and verification completed successfully.`
          });
        
        # Create a verification log for the comment
        node scripts/verify_production_integrity.mjs > verification.log 2>&1 || true
        
    - name: Fail if verification failed
      if: failure()
      run: |
        echo "❌ Verification failed. Check the logs for details."
        exit 1
