name: Test Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running'
        required: false
        default: 'Manual trigger'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show reason
        run: |
          echo "Workflow triggered with reason: ${{ github.event.inputs.reason }}"
          echo "Event name: ${{ github.event_name }}"
